### ISSUE TITLE
[Issue] Incompatible with CustomFov

### ISSUE THREAD

**Issue by ghost** [Gluton-Official/QuickSpyglasser#1]
https://www.curseforge.com/minecraft/mc-mods/custom-fov-fabric

If you have CustomFOV installed, QuickSpyglasser gets overridden and doesn't zoom in. Using the spyglass regularly or using [WI Zoom](https://www.curseforge.com/minecraft/mc-mods/wi-zoom) with CustomFov works fine. Is there a way to make QuickSpyglasser take priority?

**Comment by Gluton-Official** [comment]
Hi bendooms,

Thank you for reporting this issue, I have determined that the easiest solution is for CustomFoV to add spyglass support, which would subsequently fix the issue with QuickSpyglasser. I have submitted a PR for CustomFoV with a fix and am waiting for a response from them.

Gluton

**Comment by ghost** [comment]
Thank you!

**Comment by Gluton-Official** [comment]
TheIllusiveC4 merged my PR, so it should all be good now!
